on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

name: weekly-tests

jobs:
  # duckdb-CDMConnector:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: duckdb-CDMConnector
  #
  # local-omopgenerics:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: local-omopgenerics

  sqlserver-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: sqlserver-CDMConnector
    secrets:
      CDM5_SQL_SERVER_SERVER: ${{ secrets.CDM5_SQL_SERVER_SERVER }}
      CDM5_SQL_SERVER_USER:   ${{ secrets.CDM5_SQL_SERVER_USER }}
      CDM5_SQL_SERVER_PASSWORD: ${{ secrets.CDM5_SQL_SERVER_PASSWORD }}

  # postgres-CDMConnector:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: postgres-CDMConnector
  #
  # snowflake-CDMConnector:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: snowflake-CDMConnector
  #
  # redshift-CDMConnector:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: redshift-CDMConnector
