on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

name: postgres-CDMConnector

jobs:
  postgres-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: postgres-CDMConnector
    secrets:
      CDM5_POSTGRESQL_PASSWORD: ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}
      CDM5_POSTGRESQL_SERVER: ${{ secrets.CDM5_POSTGRESQL_SERVER }}
      CDM5_POSTGRESQL_USER: ${{ secrets.CDM5_POSTGRESQL_USER }}
