on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

name: weekly-tests

permissions:
  id-token: write

jobs:
  duckdb-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: duckdb-CDMConnector

  local-omopgenerics:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: local-omopgenerics

  sqlserver-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: sqlserver-CDMConnector
    secrets:
      CDM5_SQL_SERVER_SERVER: ${{ secrets.CDM5_SQL_SERVER_SERVER }}
      CDM5_SQL_SERVER_USER:   ${{ secrets.CDM5_SQL_SERVER_USER }}
      CDM5_SQL_SERVER_PASSWORD: ${{ secrets.CDM5_SQL_SERVER_PASSWORD }}

  postgres-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: postgres-CDMConnector
    secrets:
      CDM5_POSTGRESQL_PASSWORD: ${{ secrets.CDM5_POSTGRESQL_PASSWORD }}
      CDM5_POSTGRESQL_SERVER: ${{ secrets.CDM5_POSTGRESQL_SERVER }}
      CDM5_POSTGRESQL_USER: ${{ secrets.CDM5_POSTGRESQL_USER }}

  # TODO snowflake connection is not working on GitHub actions
  # snowflake-CDMConnector:
  #   uses: ./.github/workflows/test-template.yaml
  #   with:
  #     DB_TO_TEST: snowflake-CDMConnector
  #   secrets:
  #     CDM_SNOWFLAKE_CONNECTION_STRING: ${{ secrets.CDM_SNOWFLAKE_CONNECTION_STRING }}
  #     CDM_SNOWFLAKE_PASSWORD: ${{ secrets.CDM_SNOWFLAKE_PASSWORD }}
  #     CDM_SNOWFLAKE_USER: ${{ secrets.CDM_SNOWFLAKE_USER }}

  redshift-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: redshift-CDMConnector
    secrets:
      CDM5_REDSHIFT_SERVER: ${{ secrets.CDM5_REDSHIFT_SERVER }}
      CDM5_REDSHIFT_PASSWORD: ${{ secrets.CDM5_REDSHIFT_PASSWORD }}
      CDM5_REDSHIFT_USER: ${{ secrets.CDM5_REDSHIFT_USER }}
