on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

name: sqlserver-CDMConnector

jobs:
  sqlserver-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: sqlserver-CDMConnector
    secrets:
      CDM5_SQL_SERVER_SERVER: ${{ secrets.CDM5_SQL_SERVER_SERVER }}
      CDM5_SQL_SERVER_USER:   ${{ secrets.CDM5_SQL_SERVER_USER }}
      CDM5_SQL_SERVER_PASSWORD: ${{ secrets.CDM5_SQL_SERVER_PASSWORD }}
