on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

name: redshift-CDMConnector

jobs:
  redshift-CDMConnector:
    uses: ./.github/workflows/test-template.yaml
    with:
      DB_TO_TEST: redshift-CDMConnector
    secrets:
      CDM5_REDSHIFT_SERVER: ${{ secrets.CDM5_REDSHIFT_SERVER }}
      CDM5_REDSHIFT_PASSWORD: ${{ secrets.CDM5_REDSHIFT_PASSWORD }}
      CDM5_REDSHIFT_USER: ${{ secrets.CDM5_REDSHIFT_USER }}
